### ISSUE TITLE
 generated repository should return concrete type instead of interface

### ISSUE THREAD

**Issue by hhow09** [sunboyy/repogen#42]
**Is your feature request related to a problem? Please describe.**
generated repository should return concrete type instead of interface

currently `NewUserRepository` in example is returning interface.
However as suggestion in go codereview
> Go interfaces generally belong in the package that uses values of the interface type, not the package that implements those values. The implementing package should return concrete (usually pointer or struct) types [^1]

`*UserRepositoryMongo` should be returned.

btw you can assert the implementation in test file
```go
// user_repo_test.go
var _ UserRepository  = (*UserRepositoryMongo)(nil)
```

**Describe the solution you'd like**
return concrete type

[^1]: https://go.dev/wiki/CodeReviewComments#interfaces

**Comment by sunboyy** [comment]
I see. I will work on it.

**Comment by sunboyy** [comment]
Fixed by https://github.com/sunboyy/repogen/pull/44
